services:
  redbot:
    container_name: redbot
    build:
      context: .
      dockerfile: Dockerfile
    image: redbot-custom:latest
    restart: unless-stopped
    environment:
      TOKEN: "${DISCORD_BOT_TOKEN}"
      PREFIX: "${DISCORD_BOT_PREFIX:-!}"
      OWNER: "${DISCORD_OWNER_ID}"
      TZ: "${TZ:-UTC}"
      REDBOT_VERSION: "${REDBOT_VERSION:-}"
      EXTRA_ARGS: "${EXTRA_ARGS:-}"
    volumes:
      - ./redbot-data:/data
